import { defineConfig, type Plugin } from 'vite';
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';
import pkg from './package.json' with { type: 'json' };

/** What this build is: package version, commit and build time. Shown in Settings. */
function buildInfo() {
  let sha = (process.env.GITHUB_SHA ?? '').slice(0, 7);
  if (!sha) {
    try { sha = execSync('git rev-parse --short=7 HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch { sha = 'local'; }
  }
  return { version: pkg.version, sha, built: new Date().toISOString() };
}
const BUILD = buildInfo();

/**
 * Emits sw.js at build time: a cache-first service worker whose precache list is
 * the exact set of files in the build, versioned by their content. A new build
 * installs beside the old cache and only takes over when the page asks it to,
 * so an update never interrupts a match in progress.
 */
function serviceWorker(): Plugin {
  return {
    name: 'scopa-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map') && !(f.endsWith('.woff2') && !/-latin-/.test(f)) && !f.endsWith('.woff'));
      const publicFiles = ['manifest.webmanifest', 'icons/icon.svg', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-512.png', 'icons/apple-touch-icon.png'];
      const all = ['./', ...files, ...publicFiles];
      const hash = createHash('sha256');
      for (const f of files) {
        const item = bundle[f];
        hash.update(f).update(item.type === 'chunk' ? item.code : typeof item.source === 'string' ? item.source : Buffer.from(item.source));
      }
      const version = hash.digest('hex').slice(0, 12);
      this.emitFile({ type: 'asset', fileName: 'version.json', source: JSON.stringify({ ...BUILD, cache: `scopa-${version}` }) });
      const source = `// generated by vite.config.ts
const CACHE = 'scopa-${version}';
const PRECACHE = ${JSON.stringify(all)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
});
self.addEventListener('message', (e) => {
  if (e.data === 'skipWaiting') self.skipWaiting();
  if (e.data === 'cacheInfo') e.source && e.source.postMessage({ type: 'cacheInfo', cache: CACHE, files: PRECACHE.length });
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('scopa-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin || url.pathname.endsWith('/version.json')) return;
  e.respondWith(caches.open(CACHE).then((c) => c.match(req, { ignoreSearch: true })).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
    return res;
  }).catch(() => caches.open(CACHE).then((c) => c.match('./')))));
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [serviceWorker()],
  define: { __BUILD__: JSON.stringify(BUILD) },
  server: { port: 8134, strictPort: true },
  preview: { port: 8135, strictPort: true },
  build: { target: 'es2022', assetsInlineLimit: 0 },
  test: { include: ['tests/**/*.test.ts'], testTimeout: 120000 },
});
